import os
import json
import time
from groq import Groq

# C2: Simple TTL cache — keyed by (signal, confidence), expires after 300s.
_NLP_CACHE: dict = {}
_NLP_CACHE_TTL = 300  # seconds


def _cache_key(report: dict) -> str:
    return f"{report.get('FINAL_SIGNAL','')}_{report.get('CONFIDENCE', 0)}"

def parse_report_to_prompt(report: dict, symbol: str = None) -> str:
    """
    Translates the dict report generated by Super Signals into 
    a highly compressed context prompt for Groq.
    """
    symbol = symbol or report.get("SYMBOL", "Unknown")
    signal = report.get("FINAL_SIGNAL", "Unknown")
    confidence = report.get("CONFIDENCE", 0)
    
    risk_info = report.get("RISK_ADVISORY", {}) or {}
    alerts = report.get("GOVERNANCE_ALERTS", [])
    reasoning = report.get("REASONING", {})
    
    # Compress context
    context = (
        f"You are an institutional trading analyst. Summarize this {symbol} analysis in 2-3 concise sentences. "
        f"Focus on WHY the decision was made, not just restating numbers. Use trader terminology.\n\n"
        
        f"--- DATA ---\n"
        f"Asset: {symbol}\n"
        f"Signal: {signal} ({confidence}/100)\n"
    )
    
    if alerts:
        context += "Governance Warnings:\n"
        for a in alerts:
            context += f" - {a}\n"
            
    context += "Technical Readout:\n"
    context += f" - {reasoning.get('l2_confluence', 'No TF data')}\n"
    context += f" - {reasoning.get('l3_history', 'No historic data')}\n"
    context += f" - {reasoning.get('l4_news', 'No sentiment data')}\n"

    is_locked = "LOCKED" in signal.upper()
    is_wait_no_trade = ("WAIT" in signal.upper() or "NO_TRADE" in signal.upper()) and not is_locked

    if risk_info and risk_info.get("ENTRY_PRICE") and not is_locked:
        context += "\nCalculated Trade Setup (Reference Levels):\n" if is_wait_no_trade else "\nPending Limit Order Details:\n"
        context += f" - Type: {risk_info.get('ENTRY_TYPE', 'N/A')} @ {risk_info.get('ENTRY_PRICE')}\n"
        context += f" - Invalidation Stop Loss: {risk_info.get('STOP_LOSS')}\n"
        tp = " | ".join(map(str, risk_info.get("TAKE_PROFIT", [])))
        context += f" - Projected Targets: {tp}\n"
        if risk_info.get('RR_RATIO'):
            context += f" - Geometric R:R: {risk_info.get('RR_RATIO')}:1\n"
        elif risk_info.get('TP_RR_ACTUAL'):
            rr_vals = " | ".join(f"{r}x" for r in risk_info.get('TP_RR_ACTUAL', []))
            context += f" - Target R:R: {rr_vals}\n"
    else:
        context += "\nTrade Setup Details:\n"
        context += " - Entry: not provided (Trade Locked)\n" if is_locked else " - Entry: not provided\n"
        context += " - Stop Loss: not provided\n"
        context += " - Take Profit 1: not provided\n"
        context += " - Risk/Reward Ratio: not provided\n"
    
    context += (
        "\n--- END ---\n"
        "Output 2-3 sentences: WHY this decision? What's the key issue? What's the plan? "
        "Be direct. No fluff. Use terms like 'ranging', 'confluence', 'invalidation', 'R:R'. "
    )

    if is_locked:
        context += (
            "For WAIT / LOCKED decisions: The asset is in a hard protocol or critical risk lock. "
            "No trade setup (Entry, Stop Loss, Take Profit) is provided. State clearly that the market is locked "
            "due to critical risk/news and all trade execution is strictly prohibited. "
        )
    elif is_wait_no_trade:
        context += (
            "For WAIT / NO_TRADE decisions: Calculated entry, SL, and TP levels ARE shown above, "
            "but the decision is still to WAIT/HOLD because of the technical, structural, or governance reasons in the data. "
            "Do NOT claim that no entry, SL, or TP levels exist or are defined. "
            "Instead, note that despite the calculated levels above, entry is withheld/invalidated at this time due to the specific issue (e.g. low confidence, governance alert, lack of confluence, or ranging market). "
        )

    context += (
        "Only reference numbers, values, and metrics that are explicitly provided in the data above. "
        "Do not invent, assume, or estimate any figure (price, R:R ratio, percentage, etc.) that is not present in the input data."
    )
    
    return context


def generate_nlp_summary(report: dict, symbol: str = None) -> str:
    """
    Calls the Groq API to generate an NLP summary of the report.
    C2: Cached for 300s keyed by (signal, confidence) to avoid redundant API calls.
    Returns the string text or an error message.
    """
    key = _cache_key(report)
    now = time.time()
    if key in _NLP_CACHE:
        entry = _NLP_CACHE[key]
        if now - entry["ts"] < _NLP_CACHE_TTL:
            return entry["text"]

    from dotenv import load_dotenv, find_dotenv
    load_dotenv(find_dotenv())

    # Priority: GROQ_API_KEY > GROQ_AI_KEY > GROQAPIKEY
    api_key = (
        os.environ.get("GROQ_API_KEY") or 
        os.environ.get("GROQ_AI_KEY") or 
        os.environ.get("GROQAPIKEY")
    )
    
    if not api_key:
        return "[NLP Engine Offline: GROQ_API_KEY missing]"

    # Model preference order: fast/cheap first, fallback to next if model not found
    _MODELS = ["openai/gpt-oss-20b", "groq/compound-mini", "qwen/qwen3.6-27b"]

    try:
        client = Groq(api_key=api_key)
        prompt = parse_report_to_prompt(report, symbol)

        last_err = None
        for model in _MODELS:
            try:
                completion = client.chat.completions.create(
                    model=model,
                    messages=[{"role": "user", "content": prompt}],
                    temperature=0.2,
                    max_tokens=1024,
                    timeout=15
                )
                msg = completion.choices[0].message
                # openai/gpt-oss-20b is a reasoning model — content holds the
                # final answer, reasoning holds chain-of-thought. Use content only.
                reply = (msg.content or "").strip()
                if not reply:
                    last_err = Exception(f"{model} returned empty response")
                    continue
                _NLP_CACHE[key] = {"text": reply, "ts": now}
                return reply
            except Exception as e:
                err_str = str(e).lower()
                # Only fall through to next model on model-not-found errors
                if any(x in err_str for x in ["model_not_found", "does not exist", "not found", "404"]):
                    last_err = e
                    continue
                raise  # re-raise non-model errors immediately

        return "[AI analysis unavailable — no compatible model found]"

    except Exception as e:
        return "[AI analysis unavailable]"
