import os
import json
import time
from groq import Groq

# C2: Simple TTL cache — keyed by (signal, confidence), expires after 300s.
_NLP_CACHE: dict = {}
_NLP_CACHE_TTL = 300  # seconds


def _cache_key(report: dict) -> str:
    return f"{report.get('FINAL_SIGNAL','')}_{report.get('CONFIDENCE', 0)}"

def parse_report_to_prompt(report: dict, symbol: str = None) -> str:
    """
    Translates the dict report generated by Super Signals into 
    a highly compressed context prompt for Groq.
    """
    symbol = symbol or report.get("SYMBOL", "Unknown")
    signal = report.get("FINAL_SIGNAL", "Unknown")
    confidence = report.get("CONFIDENCE", 0)
    
    risk_info = report.get("RISK_ADVISORY", {}) or {}
    alerts = report.get("GOVERNANCE_ALERTS", [])
    reasoning = report.get("REASONING", {})
    
    # Compress context
    context = (
        f"You are an institutional trading analyst. Summarize this {symbol} analysis in 2-3 concise sentences. "
        f"Focus on WHY the decision was made, not just restating numbers. Use trader terminology.\n\n"
        
        f"--- DATA ---\n"
        f"Asset: {symbol}\n"
        f"Signal: {signal} ({confidence}/100)\n"
    )
    
    if alerts:
        context += "Governance Warnings:\n"
        for a in alerts:
            context += f" - {a}\n"
            
    context += "Technical Readout:\n"
    context += f" - {reasoning.get('l2_confluence', 'No TF data')}\n"
    context += f" - {reasoning.get('l3_history', 'No historic data')}\n"
    context += f" - {reasoning.get('l4_news', 'No sentiment data')}\n"
    
    if risk_info and risk_info.get("ENTRY_PRICE"):
        context += "\nPending Limit Order Details:\n"
        context += f" - Type: {risk_info.get('ENTRY_TYPE', 'N/A')} @ {risk_info.get('ENTRY_PRICE')}\n"
        context += f" - Invalidation Stop Loss: {risk_info.get('STOP_LOSS')}\n"
        tp = " | ".join(map(str, risk_info.get("TAKE_PROFIT", [])))
        context += f" - Projected Targets: {tp}\n"
        context += f" - Geometric R:R: {risk_info.get('RR_RATIO', 'N/A')}:1\n"
    
    context += (
        "\n--- END ---\n"
        "Output 2-3 sentences: WHY this decision? What's the key issue? What's the plan? "
        "Be direct. No fluff. Use terms like 'ranging', 'confluence', 'invalidation', 'R:R'."
    )
    
    return context


def generate_nlp_summary(report: dict, symbol: str = None) -> str:
    """
    Calls the Groq API to generate an NLP summary of the report.
    C2: Cached for 300s keyed by (signal, confidence) to avoid redundant API calls.
    Returns the string text or an error message.
    """
    key = _cache_key(report)
    now = time.time()
    if key in _NLP_CACHE:
        entry = _NLP_CACHE[key]
        if now - entry["ts"] < _NLP_CACHE_TTL:
            return entry["text"]

    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key:
        return "[NLP Engine Offline: GROQ_API_KEY missing]"

    try:
        client = Groq(api_key=api_key)
        prompt = parse_report_to_prompt(report, symbol)
        
        # We use a fast, cheap model because latency matters here.
        completion = client.chat.completions.create(
            model="llama-3.1-8b-instant",
            messages=[
                {"role": "user", "content": prompt}
            ],
            temperature=0.2,
            max_tokens=150
        )
        
        reply = completion.choices[0].message.content.strip()
        _NLP_CACHE[key] = {"text": reply, "ts": now}
        return reply

    except Exception as e:
        return f"[NLP Generation Failed: {e}]"
